CREATE TABLE IF NOT EXISTS app_settings (
  setting_key VARCHAR(100) PRIMARY KEY,
  setting_value TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'user',
  can_create_users BOOLEAN NOT NULL DEFAULT FALSE,
  session_version INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS monthly_ads (
  id BIGSERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  sku VARCHAR(120),
  asin VARCHAR(120),
  category VARCHAR(200),
  month_name VARCHAR(20),
  impressions INTEGER DEFAULT 0,
  clicks INTEGER DEFAULT 0,
  page_views INTEGER DEFAULT 0,
  sessions INTEGER DEFAULT 0,
  ctr DOUBLE PRECISION DEFAULT 0,
  spend DOUBLE PRECISION DEFAULT 0,
  sales DOUBLE PRECISION DEFAULT 0,
  total_units INTEGER DEFAULT 0,
  total_sales DOUBLE PRECISION DEFAULT 0,
  acos DOUBLE PRECISION DEFAULT 0,
  tacos DOUBLE PRECISION DEFAULT 0,
  conversion_rate DOUBLE PRECISION DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_monthly_ads_month ON monthly_ads(month_name);
CREATE INDEX IF NOT EXISTS idx_monthly_ads_sku ON monthly_ads(sku);
CREATE INDEX IF NOT EXISTS idx_monthly_ads_asin ON monthly_ads(asin);
CREATE INDEX IF NOT EXISTS idx_monthly_ads_category ON monthly_ads(category);

CREATE TABLE IF NOT EXISTS weekly_ads (
  id BIGSERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  sku VARCHAR(120),
  week_range VARCHAR(50),
  spend DOUBLE PRECISION DEFAULT 0,
  sales DOUBLE PRECISION DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_identity (
  id BIGSERIAL PRIMARY KEY,
  user_email VARCHAR(255) NOT NULL UNIQUE,
  latest_phone VARCHAR(30) NULL,
  brand_name VARCHAR(120) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_data_logs (
  id BIGSERIAL PRIMARY KEY,
  user_identity_id BIGINT NULL REFERENCES user_identity(id) ON DELETE SET NULL,
  member_visit_id VARCHAR(64) NULL,
  user_email VARCHAR(255) NOT NULL,
  phone_number VARCHAR(30) NOT NULL,
  brand_name VARCHAR(120) NULL,
  option_used VARCHAR(80) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  file_path TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_user_data_logs_email ON user_data_logs(user_email);
CREATE INDEX IF NOT EXISTS idx_user_data_logs_phone ON user_data_logs(phone_number);
CREATE INDEX IF NOT EXISTS idx_user_data_logs_option ON user_data_logs(option_used);

CREATE TABLE IF NOT EXISTS campaign_report (
  id BIGSERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  campaign_name VARCHAR(255),
  impressions INTEGER DEFAULT 0,
  clicks INTEGER DEFAULT 0,
  spend DOUBLE PRECISION DEFAULT 0,
  sales DOUBLE PRECISION DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS search_term_report (
  id BIGSERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  search_term VARCHAR(255),
  impressions INTEGER DEFAULT 0,
  clicks INTEGER DEFAULT 0,
  spend DOUBLE PRECISION DEFAULT 0,
  sales DOUBLE PRECISION DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
